In [1]:
import numpy as np

### 데이터 사이언스 패키지

패키지안에 어떤 메소드(함수)가 있는지 아주 잘 기억하자
*   numpy : 선형대수(oepnCV), 행렬(벡터),
*   pandas : csv, excel같은 파일을 가져와서 데이프레임에 넣고 데이터를 가공
*   matplotlib :
*   seaborn :

머신러닝용 라이브러리
*   scikit-learn



In [2]:
print(np.__version__)

1.26.4


In [13]:
# 파이썬의 리스트는 다양한 데이터 타입을 포함할 수 있다.
# numpy에서는 ndarray 생성시 데이터 타입을 하나로 통일하게 된다.
arr = np.array([1,2,3,4], dtype=int)
arr

array([1, 2, 3, 4])

In [4]:
type(arr)

numpy.ndarray

In [6]:
arr0 = np.array([1.,2.,3.,4.])
arr0

array([1., 2., 3., 4.])

In [8]:
# 1차원리스트
mylist1 = [1, 2, 3, 4]

In [7]:
# 2차원 리스트
mylist2 = [[1, 2, 3, 4],
           [5, 6, 7, 8]]

In [11]:
arr1 = np.array(mylist1)
arr1

array([1, 2, 3, 4])

In [12]:
arr2 = np.array(mylist2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr1.shape

(4,)

In [16]:
arr2.shape

(2, 4)

In [14]:
mylist = [1, 3.14, 'hello', '1234']
mylist

[1, 3.14, 'hello', '1234']

In [17]:
mylist[1]

3.14

In [18]:
mylist[2]

'hello'

In [19]:
arr = np.array([1, 2, 3, 3.14])
arr

array([1.  , 2.  , 3.  , 3.14])

In [20]:
arr = np.array([1, 2, 3, 3.14], dtype=int)
arr

array([1, 2, 3, 3])

In [21]:
arr = np.array([1, 3.14, 'abc', '1234'])
arr

array(['1', '3.14', 'abc', '1234'], dtype='<U32')

In [22]:
arr[0] + arr[1]

'13.14'

In [23]:
temp = '1234'
value = int(temp)
type(value)

int

In [24]:
arr = np.array([1, 3.14, '1234'], dtype=int)
arr

array([   1,    3, 1234])

1. 슬라이싱

In [25]:
temp = range(10)
temp
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
myList = list(range(10))
arr0 = np.array(myList)
arr0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr.shape
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[0]

0

In [33]:
arr[5]

5

In [34]:
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [35]:
arr[-1]

9

In [36]:
arr[-10]

0

In [37]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [38]:
arr2d.shape

(3, 4)

In [39]:
arr2d[0, 2]

3

In [40]:
arr2d[2, 1]

10

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[:5]

array([0, 1, 2, 3, 4])

In [44]:
arr[1:5]

array([1, 2, 3, 4])

In [43]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [47]:
arr2d[0, :]

array([1, 2, 3, 4])

In [48]:
arr2d[0, :].shape

(4,)

In [49]:
arr2d[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
arr2d[:2, 2:]

array([[3, 4],
       [7, 8]])

In [51]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])
idx = [1, 3, 5]
arr[idx]

array([23,  7, 65])

In [52]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [53]:
# 0행과 1행을 fancy indexing으로 지정
arr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
# 1,2,3행을 fancy indexing으로 지정
arr2d[:, [1, 2, 3]]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [55]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [56]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [57]:
myTrueFalse = [True, False, True]

In [58]:
# arr의 갯수만큼 boolean index의 리스트를 생성해줘야한다.
arr[myTrueFalse]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 3

In [64]:
Bindex = arr>2
Bindex

array([False, False,  True,  True,  True,  True,  True])

In [65]:
arr[Bindex]

array([3, 4, 5, 6, 7])

In [61]:
myTrueFalse = [True, False, True, False, True, False, True]

In [62]:
arr[myTrueFalse]

array([1, 3, 5, 7])

In [66]:
# result에는 boolean index배열이 저장된다.
result = arr2d > 2

In [67]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [68]:
arr2d[ arr2d > 2 ]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [69]:
arr2d[ arr2d < 5 ]

array([1, 2, 3, 4])

In [74]:
arr2d[( arr2d > 2 ) & ( arr2d < 5 )]

array([3, 4])

In [75]:
# arr2d의 값이 2보다 크고 5보다 작은 값을 boolean indexing 변수로 저장
result = ( arr2d > 2 ) & ( arr2d < 5 )
result

array([[False, False,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# 배열을 myArray2d = [[3,1,2,4],[5,6,3,4],[2.7,8,9]]
# 1번방법  수작업 faney indexing
# 2번방법  조건필터 Boolean indexing
# Boolean index을 사용하려면 ndarray로 변환
# Boolean index을 array에 적용

In [78]:
myArray2d = [[3,1,2,4],[5,6,3,4],[2,7,8,9]]
myArray2d

[[3, 1, 2, 4], [5, 6, 3, 4], [2, 7, 8, 9]]

In [79]:
myArray2d = np.array(myArray2d)
myArray2d

array([[3, 1, 2, 4],
       [5, 6, 3, 4],
       [2, 7, 8, 9]])

In [80]:
myArray2d[myArray2d > 5]

array([6, 7, 8, 9])

In [81]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [82]:
arr = np.arange(start=11, stop=1, step=-1)
arr

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [83]:
# start=0, step=1
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
arr = np.arange(stop=11, start=1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
arr = np.arange(1, 10, 2)
arr

array([1, 3, 5, 7, 9])

In [88]:
arr = np.arange(start=1, stop=10, step=2)
arr

array([1, 3, 5, 7, 9])

In [89]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [91]:
test= range(1, 11)
print(test)

range(1, 11)


In [92]:
for i in range(1, 11, 2):
    print(i)

1
3
5
7
9


In [93]:
import numpy as np
a= 3
b =4
c = np.dot(a,b)
c

12

In [94]:
arr = np.array([1, 10, 5, 8, 2, 4, 3, 6, 8, 7, 9])
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [95]:
# 오름차순 정렬
arr = np.sort(arr)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [96]:
# 내림차순 정렬 -> [::-1]
np.sort(arr)[::-1]

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [98]:
arr2d = np.array([[5, 6, 7, 8],
                  [4, 3, 2, 1],
                  [10, 9, 12, 11]])
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [99]:
arr2d.shape

(3, 4)

In [100]:
# 가로방향 같은 행 데이터 안에서 정렬
np.sort(arr2d, axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [101]:
# 세로방향 열 데이터간의 정렬
np.sort(arr2d, axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [102]:
arr2d = np.array([[5, 6, 7, 8],
                  [4, 3, 2, 1],
                  [10, 9, 12, 11]])
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [103]:
np.argsort(arr2d, axis=1)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]])

In [104]:
np.sort(arr2d, axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [105]:
np.argsort(arr2d, axis=0)

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]])

In [106]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

In [107]:
b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [108]:
a + b

array([[4, 6, 8],
       [3, 5, 7]])

In [109]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

In [110]:
b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [111]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [112]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

In [113]:
b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [114]:
a - b

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [115]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

In [116]:
b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [117]:
a - b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [118]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

In [119]:
b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [120]:
a.shape, b.shape

((2, 3), (2, 3))

In [121]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

In [123]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

In [122]:
b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [124]:
a * b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [ ]:
# 행렬곱 연산이 이루어지려면 a행렬과 b행렬의 행렬곱에서는
# a(2,3), b(3,2)  => (2,2)

In [125]:
a.shape, b.shape

((2, 3), (3, 2))

In [126]:
np.dot(a, b)

array([[22, 28],
       [31, 40]])

In [127]:
a.dot(b)

array([[22, 28],
       [31, 40]])

In [ ]:
# 행렬의 나눗셈 연산

In [129]:
a = np.array([[2, 4, 6],
              [4, 6, 8]])
b = np.array([[2, 2, 2],
              [2, 2, 2]])

a/b

array([[1., 2., 3.],
       [2., 3., 4.]])

In [132]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

In [133]:
b = np.array([[3, 3, 3],
              [3, 3, 3]])

In [134]:
a + b

array([[4, 5, 6],
       [5, 6, 7]])

In [136]:
print(a + 3)
print(a - 3)
print(a * 3)
print(a / 3)

[[4 5 6]
 [5 6 7]]
[[-2 -1  0]
 [-1  0  1]]
[[ 3  6  9]
 [ 6  9 12]]
[[0.33333333 0.66666667 1.        ]
 [0.66666667 1.         1.33333333]]


In [137]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

In [138]:
b = np.array([[1],
              [2]])

In [139]:
a.shape, b.shape

((2, 3), (2, 1))

In [140]:
b * a

array([[1, 2, 3],
       [4, 6, 8]])

In [141]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

In [142]:
b = np.array([1, 2, 3])

In [143]:
a * b

array([[ 1,  4,  9],
       [ 2,  6, 12]])

In [144]:
import pandas as pd

In [145]:
# python의 리스트 [1,2,3,4] Series함수에 넣으면 pandas.Series데이터 변수를 생성
pd.Series([1, 2, 3, 4])

0    1
1    2
2    3
3    4
dtype: int64

In [146]:
a = [1, 2, 3, 4]

In [147]:
pd.Series(a)

0    1
1    2
2    3
3    4
dtype: int64

In [150]:
index = ['a', 'b', 'c', 'd']
mylist = [1, 2, 3, 4]
test = pd.Series(mylist)
print(test)
# 이 셀에서는 Pandas seires 데이터를 생성

0    1
1    2
2    3
3    4
dtype: int64


In [152]:
# 2차원 리스트로 values값을 생성
subway1 = [['1호선','서울역', 17896, 15468],
           ['2호선','강남', 22794, 21657],
           ['3호선','신사', 24131, 25592]]

In [153]:
# DataFrame의 왼쪽 첫번째 열은 index이다.
# DataFrame의 첫번째 행은 columns이다.
# 실제 data가 저장된 부분은 values라고 부른다.
# 실제 데이터프레임이 저장되지는 않는다.
pd.DataFrame(subway1)

0    1      2      3
0  1호선  서울역  17896  15468
1  2호선   강남  22794  21657
2  3호선   신사  24131  25592

In [154]:
# df1이라는 이름으로 데이터프레임이 저장(생성)
df1 = pd.DataFrame(subway1)
df1

0    1      2      3
0  1호선  서울역  17896  15468
1  2호선   강남  22794  21657
2  3호선   신사  24131  25592

In [155]:
df1.columns = ['노선명', '역명', '승차총승객수','하차총승객수']
df1

노선명   역명  승차총승객수  하차총승객수
0  1호선  서울역   17896   15468
1  2호선   강남   22794   21657
2  3호선   신사   24131   25592

In [157]:
# 데이터프레임을 생성할 때, dict타입으로 생성하면, columns와 values를 입력하고 시작
# dict의 key값은 column
# dict의 value는 values->리스트
subway2 = {'지하철노선':['1호선', '2호선', '3호선'],
            '역명': ['서울역','강남','신사'],
            '승차총승객수': [17896, 22794, 24131],
            '하차총승객수': [15468, 21657, 25592]
           }
df2 = pd.DataFrame(subway2)
df2

지하철노선   역명  승차총승객수  하차총승객수
0   1호선  서울역   17896   15468
1   2호선   강남   22794   21657
2   3호선   신사   24131   25592

In [158]:
df1

노선명   역명  승차총승객수  하차총승객수
0  1호선  서울역   17896   15468
1  2호선   강남   22794   21657
2  3호선   신사   24131   25592

In [159]:
# index값을 특정 column으로 대치하
df1.index = df1['노선명']
df1

노선명   역명  승차총승객수  하차총승객수
노선명                          
1호선  1호선  서울역   17896   15468
2호선  2호선   강남   22794   21657
3호선  3호선   신사   24131   25592

In [160]:
df1['역명']

노선명
1호선    서울역
2호선     강남
3호선     신사
Name: 역명, dtype: object

pandas.core.series.Series