In [2]:
import torch
import pandas as pd
from torch import nn
from torch import optim
from torch.utils.data import Dataset, DataLoader, random_split

In [3]:
class CustomDataset(Dataset):
    def __init__(self, file_path):
        df = pd.read_csv(file_path)
        self.x = df.iloc[:, 0].values
        self.y = df.iloc[:, 1].values
        self.length = len(df)

    def __getitem__(self, index):
        x = torch.FloatTensor([self.x[index] ** 2, self.x[index]])
        y = torch.FloatTensor([self.y[index]])
        return x, y

    def __len__(self):
        return self.length

In [4]:
class CustomModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = nn.Linear(2, 1)

    def forward(self, x):
        x = self.layer(x)
        return x

In [9]:
dataset = CustomDataset("/content/non_linear.csv")

train_ratio = 0.8
valid_ratio = 0.1
test_ratio = 0.1

dataRatio = [train_ratio,valid_ratio,test_ratio]

dataset_size = len(dataset)
train_size = int(dataset_size * dataRatio[0])
validation_size = int(dataset_size * dataRatio[1])
test_size = dataset_size - train_size - validation_size

dataNum = [train_size, validation_size, test_size]

In [10]:
train_dataset, validation_dataset, test_dataset = random_split(dataset, dataNum)
print(f"Training Data Size : {len(train_dataset)}")
print(f"Validation Data Size : {len(validation_dataset)}")
print(f"Testing Data Size : {len(test_dataset)}")

Training Data Size : 160
Validation Data Size : 20
Testing Data Size : 20


In [11]:
train_dataloader = DataLoader(train_dataset, batch_size=16, shuffle=True, drop_last=True)
validation_dataloader = DataLoader(validation_dataset, batch_size=4, shuffle=True, drop_last=True)
test_dataloader = DataLoader(test_dataset, batch_size=4, shuffle=True, drop_last=True)

In [14]:
count = 0
for x,y in validation_dataloader:
    # 5번 출력
    if count>1:
        break
    print(x)
    print(y)
    count+=1

tensor([[40.9600, -6.4000],
        [ 1.2100, -1.1000],
        [ 2.8900, -1.7000],
        [10.8900, -3.3000]])
tensor([[138.1000],
        [  6.4800],
        [ 12.7900],
        [ 39.7100]])
tensor([[ 0.8100, -0.9000],
        [36.0000,  6.0000],
        [57.7600,  7.6000],
        [79.2100, -8.9000]])
tensor([[  4.4500],
        [102.1200],
        [166.8600],
        [260.8500]])
