## 텐서의 생성

In [6]:
import torch
#torchArray = torch.tensor([1,2,3,4])
torchArray = torch.FloatTensor([1,2,3,4])
print(torchArray)
print(type(torchArray))
print(torchArray.dtype)
print(torchArray.device)
print(torchArray.ndim)
print(torchArray.shape)
print(torchArray.size())

tensor([1., 2., 3., 4.])
<class 'torch.Tensor'>
torch.float32
cpu
1
torch.Size([4])
torch.Size([4])


In [4]:
import numpy as np

nparray = np.array([1,2,3,4], dtype=np.float32)
print(nparray)
print(type(nparray))

[1. 2. 3. 4.]
<class 'numpy.ndarray'>


### 난수 생성

In [10]:
import torch

# 1행 2열짜리 난수를 생성해준다.(0~1사이의 난수를 생성)
tensor = torch.rand(1,10)
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.4473, 0.3953, 0.3611, 0.0698, 0.2121, 0.2741, 0.3455, 0.9719, 0.1093,
         0.3950]])
torch.Size([1, 10])
torch.float32
cpu


## 차원 변환

In [12]:
import torch
#shape(1,2) 1행 2열
tensor = torch.rand(1,2)
print(tensor)
print(tensor.shape)
#reshape(2,1) 2행 1열
tensor = tensor.reshape(2,1)
print(tensor)
print(tensor.shape)

tensor([[0.8065, 0.3290]])
torch.Size([1, 2])
tensor([[0.8065],
        [0.3290]])
torch.Size([2, 1])


## 텐서 생성시 자료형 설정

In [13]:
import torch

tensor = torch.tensor([1,2,3,4], dtype=torch.float32)
print(tensor)
print(tensor.dtype)

tensor([1., 2., 3., 4.])
torch.float32


## 장치 설정
CPU에서 신경망을 구성할지, GPU에서 구성할지 설정

In [2]:
import torch

# 현재 torch가 사용할 수 있는 장치를 확인
# if torch.cuda.is_available() -> nvidia GPU를 사용할 수 있다면
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
cpu = torch.tensor([1,2,3])
gpu = torch.tensor([1,2,3], device=device)
print(cpu)
print(gpu)
print(device)

tensor([1, 2, 3])
tensor([1, 2, 3], device='cuda:0')
cuda:0


## 장치를 GPU로 전환

In [3]:
# cpu -> gpu로 전환
gpu1 = cpu.cuda()
print(gpu1)
print(gpu1.device)

tensor([1, 2, 3], device='cuda:0')
cuda:0


## numpy -> Tensor로 변환

In [4]:
import torch

import numpy as np

# 기존에 읽어온 numpy ndarray가 있다고 가정
npArray = np.array([1,2,3,4])
# numpy -> tensor
tensor = torch.from_numpy(npArray)
print(tensor)
print(type(tensor))

# tensor -> numpy
npArray1 = tensor.numpy()
print(npArray1)
print(type(npArray1))

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>


## 장치변환 + 넘파이변환

In [12]:
import torch

# tensor[1,2,3,4]를 생성 하는데 GPU에 생성한다.
tensor = torch.tensor([1,2,3,4], device=torch.device("cuda:0"))

# cpu로 전환 + numpy로 변환
npArray = tensor.cpu().numpy()
print(tensor)
print(tensor.device)

tensor([1, 2, 3, 4], device='cuda:0')
cuda:0


In [ ]:
x, y = 1, 3